### ISSUE TITLE
Fluid Colums inside Expanded Rows ?

### ISSUE THREAD

**Issue by sh0umik** [jamesblasco/fluid_layout#2]
My Question is How can I put responsive Fluid Cells inside SliverToBoxAdapter ? 

```
SliverToBoxAdapter(
                        child: Container(
                          margin: EdgeInsets.symmetric(vertical: 12),
                          padding: EdgeInsets.symmetric(vertical: 12),
                          color: Colors.green,
                          height: 200,
                          child: Center(child: Text('Expanded')),
                        ),
                      ),
```

I want to put or make content fluid inside expaned. I tried putting `Fluid()` inside and it works for padding but how can i put fluid cells inside fluid container ? Also all the examples in the lib lacks this example. Where there is expanded fluid widgets there are no fluid cells inside it ? it this because its not doable ? 

Logically i tried this but i does not work 

```
SliverToBoxAdapter(
                child: Container(
                  decoration: BoxDecoration(
                    color: Colors.deepPurple,
                  ),
                  child: SliverFluid(
                    sliver: SliverFluidGrid(
                      children: [
                        FluidCell.withFluidHeight(
                          size: context.fluid(2),
                          heightSize: context.fluid(2),
                          child: Container(
                            decoration: BoxDecoration(
                                color: Colors.deepPurple
                            ),
                            child: Image(
                              fit: BoxFit.contain,
                              image: instituteInfo.hasPicture()
                                  ? NetworkImage(instituteInfo.picture.avatar)
                                  : AssetImage(
                                  "assets/imgs/logo-placeholder.png"),
                            ),
                          ),
                        ),
                        FluidCell.withFluidHeight(
                          size: context.fluid(10),
                          heightSize: context.fluid(2),
                          child: Container(
                            decoration: BoxDecoration(
                                color: Colors.deepPurple
                            ),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: <Widget>[
                              ],
                            ),
                          ),
                        )
                      ],
                    ),
                  ),
                ),
              ),
```

**Comment by jamesblasco** [comment]
Hello, I don't understand what it is your question
How can I put responsive Fluid Cells inside SliverToBoxAdapter? is different to 
Fluid Columns inside Expanded Rows ?

Fluid widgets add a horizontal padding proportional to the screen size
Fluid grid widget add the same horizontal padding and distribute the fluidcells porportional to the screen size.

In a CustomScrollView you can use SliverFluidGrid, if you want to add the fluid grid inside the SliverToBoxAdapter to have to use a FluidGridView with the parameter [shrinkWrap: false] (https://api.flutter.dev/flutter/widgets/ScrollView/shrinkWrap.html) , the same as GridView or ListView inside undefined sized parent. 

If you want to use a FluidGridView without the horizontal padding, you can use the parameter fluid: false.

I will try to improve the docs. Let me know if you have any more questions

**Comment by sh0umik** [comment]
I missed the shrinkWrap property also I was wrapping the FluidGridView with Fluid, I thought that was necessary ! Just removed it and it solved my problem. Thank you, This lib is so helpful for flutter web.
